config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' =>:new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store'  

  get 'mycart' => 'carts#show', as: 'mycart'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy



  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end



  def subtract_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item.quantity > 1
      current_item.quantity -= 1
    else
      current_item.quantity = 1
    end
    current_item
  end



  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end



  def total_products
    line_items.to_a.sum { |item| item.quantity }
  end


  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :show, :update, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    redirect_to store_url
    #@carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    if @cart.id != session[:cart_id]
      redirect_to store_url
    elsif params[:id].to_i != session[:cart_id].to_i
      puts "params[:id].to_i != session[:cart_id].to_i"
      redirect_to @cart
    elsif @cart.line_items.length==0
      redirect_to store_url        
    end
    params[:show_btn_continue] = 1
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
    redirect_to @cart
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      redirect_to store_url, notice: "Вы были перенаправлены с несуществующей корзины"
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_bottom_cart.html.erb
<% if @cart %>

  <div id="bottom" class="hide-for-small-only">
    <div class="row">
      <div class="cart">
          
          <% if @cart.total_products==0 %>
            <span>Ваша корзина пуста.</span>
          <% else %>
              В вашей <%= link_to "корзине", @cart %>
              <span>
                <%= link_to @cart do %>
                  <b><%= @cart.total_products  %> </b>
                  <%= Russian.pluralize(@cart.total_products,"товар", "товара", "товаров") %>  
                <% end %>
              </span>
              на сумму  
              <span>
                <b> <%= number_to_currency(@cart.total_price) %> &nbsp</b>
              </span>
            
              <% if (defined?(show_btn_continue)) %>
                <% if (show_btn_continue.to_i==1) %>
                  <%= link_to "Купить ещё", store_path, class: "small button", id: "order_button" %>
                <% else %>
                  <%= link_to "Корзина", @cart, class: "small button", id: "order_button" %>
                <% end %>

              <% else %>
                <%= link_to "Корзина", @cart, class: "small button", id: "order_button" %>
              <% end %>
          <% end %>
      </div>
    </div>
  </div>

  <div id="bottom_mobile" class="show-for-small-only">
    <% if @cart.total_products!=0 %>
      <% if (defined?(show_btn_continue)) %>
        <% if (show_btn_continue.to_i==1) %>
          
        <% else %>
          <%= link_to @cart, class: "tiny button", id: "order_button" do %>
            <%= image_tag("cart.png") %> 
          <% end %>
        <% end %>

      <% else %>
        <%= link_to @cart, class: "tiny button", id: "order_button" do %>
          <%= image_tag("cart.png") %> 
        <% end %>
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/carts/_cart.html.erb
<table class="main_cart">
  
  
  <%= render(@cart.line_items) %>

   <tr>
    <th></th>
    <th>
      Всего:
      <%= number_to_currency(@cart.total_price) %>
    </th>
    <th>   
    </th>
  </tr>
</table>
<%= button_to "Оформить заказ", new_order_path, method: :get, class: "button success right" %>   

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="row">

  <p id="notice"><%= notice %></p>

  <h2>Ваша корзина</h2>


  <%= render @cart %>

</div>