config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' =>:new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store'  

  get 'mycart' => 'carts#show', as: 'mycart'

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  UNIT_TYPES = %w(мл. шт. г.)

  belongs_to :category
  has_many :line_items
  has_attached_file :image, :styles => { :medium => "200x200>", :thumb => "50x50>" }, :default_url => "/images/:style/missing.png"

  before_destroy :ensure_not_referenced_by_any_line_item


  validates_attachment :image,
    :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] }

  validates :title, :description, :price, :producer, :category, presence: true
  validates :price, :volume, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  #validates :units, inclusion: {in: UNIT_TYPES }
  
  
  def get_url
    "#{id}-#{producer.parameterize}-#{title.parameterize}"
  end



  private 

    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else 
        errors.add(:base, "Существуют товарные позиции")
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authorize, only: [:show]

  include CurrentCart
  before_action :set_cart
  before_action :set_product, only: [:show, :edit, :update,:destroy]
 
  

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url, notice: "Товар \"#{@product.title}\" успешно добавлен!" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)        
        format.html { redirect_to product_url, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    respond_to do |format|
      if @product.destroy    
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit, notice: @product.errors }
        format.json { head :no_content }
      end
    end
  end

  def get_line_item
    @line_item = LineItem.where(product_id: :id, cart_id: session[:cart_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :volume, :category_id, :country, :producer, :image, :units, :article)
    end

    

    # Use strong_parameters for attribute whitelisting
    # Be sure to update your create() and update() controller methods.

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Основная информация:</legend>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :producer %><br>
      <%= f.text_field :producer %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, :class => "tinymce", rows: 12 %>
      <%= tinymce :description %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :volume %><br>
      <%= f.text_field :volume %>
    </div>
    <div class="field">
      <%= f.label :units %><br>
      <%=  f.select :units, Product::UNIT_TYPES, prompt: 'Выберите из списка:' %>
    </div>
    <div class="field">
      <%= f.label :category_id %> <br>
      <% if params[:category_id].present? then @product.category_id = params[:category_id] end %>
      <%= f.text_field :category_id, :class => 'hidden category_id_input', value: @product.category_id %>
      <%= render('categories/all_categories', category: Category.find(1)) %>
      <script type="text/javascript">
        curr_cat = $('#product_category_id').val();
        $('#category_'+curr_cat).addClass('current_cat');
      </script>
    </div>
    <div class="field">
      <%= f.label :country %><br>
      <%= f.text_field :country %>
    </div>
    <div class="field">
      <%= f.label :article %><br>
      <%= f.text_area :article, :class => "tinymce", rows: 12 %>
     </div>
  </fieldset>
  <fieldset>
    <legend>Изображение:</legend>
    <p class="text-center">
      <%= image_tag @product.image.url(:medium) %>
    </p>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
      
    </div>
  </fieldset>
  <fieldset>  
  <div class="actions">
    <ul class="button-group">
      <li>
        <%= link_to '←Назад', products_path, class: "button secondary" %>
      </li>
      <li>
        <%= f.submit "Сохранить", class: "button" %>
      </li>
    </ul>
  </div>
<% end %>
<%= button_to 'Удалить товар', @product,  method: :delete, data: { confirm: 'Вы уверены?'}, class: "button" %>

app/views/products/_product.html.erb
<li>
  <div id="product_<%= product.id %>" class="product panel">

    <div class="im_desc">
      <div class="description">
        <%= link_to (sanitize(strip_tags(product.description).first(128))+"..."), product_path( id:  product.get_url ), title: product.title %>
      </div>  
      <div class="image">
        <%= image_tag product.image.url(:medium) %>
      </div>
    </div>
    <p>
      <%= link_to product_path( id:  product.get_url ), title: product.title do  %> 
       <b> <%= product.producer %> </b> - <%= (product.title.first(54)) %>
       <% end %>
    </p>
    <p class="product_price">
      <span class="right"><%=  number_to_currency(product.price) %></span>
    </p>  
    <% if User.find_by(id: session[:user_id]) %>
      <%= link_to "Править", edit_product_path(product), class: "tiny button buy_product" %>
    <% else %>
      <% if product.line_items.where(cart_id: session[:cart_id]).length==0 %>
        <%= button_to "Купить", line_items_path(product_id: product), class: "tiny button buy_product", remote:true %>
      <% else %>
        <%= button_to "Добавлено #{product.line_items.where(cart_id: session[:cart_id]).first.quantity}шт.", line_items_path(product_id: product), class: "tiny button success buy_product", remote:true %>
      <% end %>
    <% end %>
    
  </div>
</li>

app/views/products/_product_path.html.haml
%nav.breadcrumbs
  =link_to "Главная", "/"
  =link_to "Каталог", category_path(1)
  -category.get_all_parents.each do |parent|
    =link_to parent.title, category_path(parent)
  =link_to category.title, category_path(category)

app/views/products/edit.html.erb
<h1>Редактирование товаров</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Панель управления товарами</h1>

<%= link_to 'Добавить товар', new_product_path, class: "button success right" %>

<ul class="small-block-grid-1 medium-block-grid-3 large-block-grid-4 xlarge-block=grid-5">
  <% @products.each do |product| %>
    <%= render 'products/product', product: product %>
  <% end %>
</ul>

<h2>Товары - потеряшки</h2>

<ol>
  <% @products.each do |product| %>
    <% if (product.category.get_all_subcats_ids.length != 0) || (product.category.id == 1) %>
      <li>
      <%= link_to product.title, edit_product_path(product) %>
      </li>
    <% end %>
  <% end %>
</ol>

app/views/products/new.html.erb
<h1>Добавление нового товара</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<div id="product_<%= @product.id %>" class="row">
  

  

  <div class="medium-3 large-4 columns" style="text-align:center;">
    <%= image_tag @product.image.url() %>
  </div>
  <div class="medium-9 large-8 columns">
    <%= render 'product_path', category: Category.find(@product.category.id) %>
    <h1>
      <%= @product.title %>
    </h1>
    <p>
      <strong><%= @product.producer %></strong>
      
    </p>
    <p>
      <%= sanitize(@product.description) %>
    </p>
  
    <p>
    <strong>Цена:</strong>
      <%= number_to_currency(@product.price) %> за <%= (@product.volume.to_i.to_s + @product.units)  %>
    </p>
 

    <% if @product.country.to_s != "" %>
      <p>
        <strong>Страна происхождения:</strong>
        <%= @product.country %>
      </p>
    <% end %>

    <ul class="button-group">
      <li>
        <%= link_to '←Назад', 'javascript:history.go(-1);', class: "secondary button" %>
      </li>
      <% if User.find_by(id: session[:user_id]) %>
        <%= link_to 'Править', edit_product_path(@product), class: "button" %> 
      <% else %>
        <li>
          <% if @product.line_items.find_by(cart_id: session[:cart_id]) %>
            <%= button_to ("Добавлено " + @product.line_items.find_by(cart_id: session[:cart_id]).quantity.to_s + " шт."), line_items_path(product_id: @product.id), class: "success button buy_product", remote:true %>
          <% else %>
            <%= button_to "Купить→", line_items_path(product_id: @product.id), class: "button buy_product", remote:true %>
          <% end %>
        </li>
      <% end %>  
    </ul>
  </div>
</div>
<% if @product.article.to_s.length > 0 %>
  <div id="article_<%= @product.id %>" class="row">
    <%= sanitize(@product.article) %>
  </div>
<% end %>