config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' =>:new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store'  

  get 'mycart' => 'carts#show', as: 'mycart'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  def total_price
    product.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_action :authorize, only: [:new, :create, :destroy]
  include CurrentCart
  before_action :set_cart, only: [:create, :index, :new, :destroy]
  before_action :set_line_item, only: [ :update, :destroy]



  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    redirect_to store_url
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
    #redirect_to store_url
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])

    if params[:add_sub] == "add"
      @line_item = @cart.add_product(product.id)    
      respond_to do |format|
        if @line_item.save
          format.js
        end
      end

    elsif params[:add_sub] == "subtract"
      @line_item = @cart.subtract_product(product.id)
      respond_to do |format|
        if @line_item.save
          format.js
        end
      end

    else
      @line_item = @cart.add_product(product.id)
      respond_to do |format|
        if @line_item.save
          format.html { redirect_to store_url }
          format.js
          format.json { render :show, status: :created, location: @line_item }
        else
          format.html { render :new }
          format.json { render json: @line_item.errors, status: :unprocessable_entity }
        end
      end
    end

  end


  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy    
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr id="<%= line_item.id %>">
  <td class="image">
    <%= link_to line_item.product do %>
      <%= image_tag line_item.product.image.url(:thumb) %>
    <% end %>
    
  </td>
  <td >   
    <b class="quantity">
      <%= line_item.quantity %>
    </b>
    &times; 
    <%= link_to line_item.product.title, line_item.product %>
    <br>
    <b class="total_sum">
      <%= number_to_currency(line_item.quantity*line_item.product.price) %>
    </b>
  </td>
  <td>
    <%= link_to line_item_path(:id => line_item.id,:show_btn_continue => 1), method: :delete, :remote => true, class: "line_btns", title: "Удалить позицию" do %>
      <%= image_tag("delete.png") %>
    <% end %>
    <%= link_to line_items_path(product_id: line_item.product.id, id: line_item.id, add_sub: "subtract",show_btn_continue: 1), method: :post, :remote => true, class: "line_btns", title: "Убавить 1шт." do %>
      <%= image_tag("minus.png") %>
    <% end %>
    <%= link_to line_items_path(product_id: line_item.product.id, id: line_item.id, add_sub: "add", show_btn_continue: 1), method: :post, :remote => true, class: "line_btns", title: "Добавить 1шт." do %>
      <%= image_tag("add.png") %>
    <% end %>
  </td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s; ",
  line_item.quantity,
  truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
$('#notice').hide();
$('#bottom').html( "<%= escape_javascript( render partial: 'carts/bottom_cart', locals: { show_btn_continue: params[:show_btn_continue] } ) %>" );
$('.cart span').effect("highlight", {}, 1000);

if ($("#<%= @line_item.id %>").length > 0){
  $("#<%= @line_item.id %> .quantity").html("<%= @line_item.quantity %>");
  $("#<%= @line_item.id %> .total_sum").html(
    "<%= number_to_currency @line_item.quantity*@line_item.product.price %>");
  $(".total_price").html("<%= number_to_currency(@line_item.cart.total_price) %>");

  $(".total_price, #<%= @line_item.id %> .total_sum, #<%= @line_item.id %> .quantity").effect(
    "highlight", {}, 1000);
};

if ($("#product_<%= @line_item.product.id %> input.buy_product").length > 0){
	$("#product_<%= @line_item.product.id %> input.buy_product").val("Добавлено <%= @line_item.quantity %> шт.").addClass("success");
}

app/views/line_items/destroy.js.erb
$('#bottom').html("<%= escape_javascript( render partial: 'carts/bottom_cart', locals: { show_btn_continue: 1 } ) %>");
$('.cart span').effect("highlight", {}, 1000);


if ($("#<%= @line_item.id %>").length>0){
    $('#<%= @line_item.id %>').remove();
};

if ($('table.main_cart tr').length<3) {
  window.location.assign("<%= store_url %>");
};

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= line_item.quantity %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>