config/routes.rb
Rails.application.routes.draw do
  resources :categories

  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' =>:new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  root to: 'store#index', as: 'store'  

  get 'mycart' => 'carts#show', as: 'mycart'

end

app/views/layouts/_admin_menu.html.erb
<li><label>Админка</label></li>
<li><%= link_to 'Просмор заказов', orders_path %></li>
<li><%= link_to 'Управление товарами', products_path %></</li>
<li><%= link_to 'Управление пользователями', users_path %></li>
<li><%= link_to 'Управление категориями', categories_path %></li>
<li><%= link_to 'Выйти', logout_path, method: :delete %></li>

app/views/layouts/_cart.html.erb
<li><label>Корзина</label></li>
<li><a href="#">Товар 1</a></li>
<li><a href="#">Товар 2</a></li>

app/views/layouts/_menu.html.erb
<li><label>Меню</label></li>
<li><a href="/">Главная</a></li>
<li><a href="/products">Товары</a></li>

app/views/layouts/_top_links.html.haml
#top_panel.clearfix
  .row
    .auth
      - if (User.find_by(id: session[:user_id]).present?)
        =link_to "Выйти", logout_path, method: "delete"
      - else
        =link_to "Войти", login_path
    .top_links
      .top_links-item
        %a{title: "О компании", href: "#"} О компании
      .top_links-item
        %a{title: "Доставка", href: "#"} Доставка
      .top_links-item
        %a{title: "Наши магазины", href: "#"} Наши магазины
      .top_links-item
        %a{title: "Акции", href: "#"} Акции
      .top_links-item
        %a{title: "Контакты", href: "#"} Контакты

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Косметичка-СПб - интернет магазин косметики" %></title>
    <script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <link rel="icon" type="image/png" href="/favicon.png" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render partial: 'carts/bottom_cart', locals: { show_btn_continue: params[:show_btn_continue], hide: params[:hide_bottom_card]  } %>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <nav class="tab-bar">
          <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
          </section>

          <section class="middle tab-bar-section">
            <h1 class="title"><%= content_for?(:title) ? yield(:title) : "Косметичка-СПб" %></h1>
          </section>

          <% if session[:user_id] %>
            <section class="right-small">
              <a class="right-off-canvas-toggle" href="#"><span><%= image_tag("cart.png") %> </span></a>
            </section>
          <% end %>

        </nav>

        <aside class="left-off-canvas-menu">
          <ul class="off-canvas-list">
            <%= render "layouts/menu" %>
          </ul>
        </aside>
        
        
        <aside class="right-off-canvas-menu">
          <ul class="off-canvas-list">
            <% if session[:user_id] %>
              <%= render "layouts/admin_menu" %>
            <% end %>
          </ul>
        </aside>
        

        <section class="main-section">

          <div class="category_nav">
            <%= render('categories/menu', category: Category.find(1)) %>
          </div> 

          <div class="main row">

            <%= yield %>
          </div>

        </section>

      <a class="exit-off-canvas"></a>

      </div>
    </div>
    
    

  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html{:lang => "ru"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) + "- Косметичка-СПб." : "Косметичка-СПб - интернет магазин косметики"
    %script{:src => "http://api-maps.yandex.ru/2.1/?lang=ru_RU", :type => "text/javascript"}
    %link{:href => "/favicon.png", :rel => "icon", :type => "image/png"}/
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: 'carts/bottom_cart', locals: { show_btn_continue: params[:show_btn_continue], hide: params[:hide_bottom_card]  }
    = render "layouts/top_links"

    .off-canvas-wrap{"data-offcanvas" => ""}
      .inner-wrap
        %nav.tab-bar
          /
            %section.left-small
              %a.left-off-canvas-toggle.menu-icon{:href => "#"}
                %span
          %section.middle.tab-bar-section
            %h1.title= content_for?(:title) ? yield(:title) : "Косметичка-СПб - интернет магазин косметики"
          - if session[:user_id]
            %section.right-small
              %a.right-off-canvas-toggle{:href => "#"}
                %span
                  = image_tag("cart.png")
        %aside.left-off-canvas-menu
          %ul.off-canvas-list
            = render "layouts/menu"
        %aside.right-off-canvas-menu
          %ul.off-canvas-list
            - if session[:user_id]
              = render "layouts/admin_menu"
        %section.main-section
          .category_nav
            = render('categories/menu', category: Category.find(1))
          .main.row
            = yield
            .yandexmetrica
              :javascript
                (function (d, w, c) {
                  (w[c] = w[c] || []).push(function() {
                      try {
                          w.yaCounter34698950 = new Ya.Metrika({
                              id:34698950,
                              clickmap:true,
                              trackLinks:true,
                              accurateTrackBounce:true,
                              webvisor:true,
                              trackHash:true
                          });
                      } catch(e) { }
                  });

                  var n = d.getElementsByTagName("script")[0],
                      s = d.createElement("script"),
                      f = function () { n.parentNode.insertBefore(s, n); };
                  s.type = "text/javascript";
                  s.async = true;
                  s.src = "https://mc.yandex.ru/metrika/watch.js";

                  if (w.opera == "[object Opera]") {
                      d.addEventListener("DOMContentLoaded", f, false);
                  } else { f(); }
                })(document, window, "yandex_metrika_callbacks");
              %noscript
                %div
                  %img{:src => "https://mc.yandex.ru/watch/34698950", :style => "position:absolute; left:-9999px;", :alt => ""}
        %a.exit-off-canvas

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Косметичка-СПб - интернет магазин косметики" %></title>
    <script src="http://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <link rel="icon" type="image/png" href="/favicon.png" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render partial: 'carts/bottom_cart', locals: { show_btn_continue: params[:show_btn_continue], hide: params[:hide_bottom_card]  } %>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <nav class="tab-bar">
          <section class="left-small">
            <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
          </section>

          <section class="middle tab-bar-section">
            <h1 class="title"><%= content_for?(:title) ? yield(:title) : "Косметичка-СПб" %></h1>
          </section>

          <% if session[:user_id] %>
            <section class="right-small">
              <a class="right-off-canvas-toggle" href="#"><span><%= image_tag("cart.png") %> </span></a>
            </section>
          <% end %>

        </nav>

        <aside class="left-off-canvas-menu">
          <ul class="off-canvas-list">
            <%= render "layouts/menu" %>
          </ul>
        </aside>
        
        
        <aside class="right-off-canvas-menu">
          <ul class="off-canvas-list">
            <% if session[:user_id] %>
              <%= render "layouts/admin_menu" %>
            <% end %>
          </ul>
        </aside>
        

        <section class="main-section">

          <div class="category_nav">
            <%= render('categories/menu', category: Category.find(1)) %>
          </div> 

          <div class="main row">

            <%= yield %>
          </div>

        </section>

      <a class="exit-off-canvas"></a>

      </div>
    </div>
    
    

  </body>
</html>